### ISSUE TITLE
Field do_not_use_batchwise_valuation does not exist on Stock Settings

### ISSUE THREAD

**Issue by MartinFulgueiras** [dvdl16/woocommerce_fusion#106]
### Current Behavior

Trying to do a stock reconciliation or material request and a message appears as per the subject. 

The problem is that no stock modifications can be done with this error.

![Screenshot from 2024-08-03 10-09-08](https://github.com/user-attachments/assets/40b1a289-7b39-4b3b-9bc0-4ed295bd48e8)

### Steps To Reproduce

1. Go to Stock reconciliation
2. try to modify a stock quantity of any product sync'ed with woocommerce
3. Submit the reconciliation
4. Error message prevents from finishing

### Expected Behavior

To modify stock quantity both in ERPNext and Woocommerce. 

### Environment and Versions

```markdown
- Frappe Version: v15.34.1
- ERPNext Version: v15.29.3
- Custom App Version: WooCommerce Fusion: v1.7.1
```

### Operating System

Other

### What browsers are you seeing the problem on?

Firefox

**Comment by dvdl16** [comment]
https://github.com/frappe/erpnext/issues/42610

**Comment by MartinFulgueiras** [comment]
Thanks
