### ISSUE TITLE
[BUG] Error in default UOM configuration

### ISSUE THREAD

**Issue by MartinFulgueiras** [dvdl16/woocommerce_fusion#107]
### Current Behavior

When trying to 'Sync this item to Erpnext'  leaving the UOM field empty in the woocommerce server configuration, the plugin should use the fallback UOM which says is "Nos". If left empty, it gives the error saying there doesn't exist a Nos UOM type. 

![Screenshot from 2024-08-03 10-58-29](https://github.com/user-attachments/assets/89f55360-fc01-409e-9e52-a9b019badc50)

I believe the reason is that the UOM is actully Nos. and not Nos without a final dot. Once I manually chose the Nos. it works ok. 

![Screenshot from 2024-08-03 10-50-42](https://github.com/user-attachments/assets/4fd09dea-926f-4c68-8b75-fec2aab2e52c)

### Steps To Reproduce

1. Go to woocommerce product list
2. Choose a sync'ed item
3. In actions, choose 'Sync this item to ERPNext'
4. Error appears

### Expected Behavior

The item should sync without problems

### Environment and Versions

```markdown
ERPNext: v15.29.3

Frappe Framework: v15.34.1

WooCommerce Fusion: v1.7.1
```

### Operating System

Other

### What browsers are you seeing the problem on?

Firefox

**Comment by dvdl16** [comment]
@MartinFulgueiras thank you for reporting this.

During setup (app installation), ERPNext creates default UoM's, one of which is `Nos` (no full stop/dot). We can confirm this here:
https://github.com/frappe/erpnext/blob/version-15/erpnext/setup/setup_wizard/data/uom_data.json#L10

Maybe this UoM was modified in your site at a later stage, to be `Nos.` (with full stop)?

This means that I won't make a change for now, hope I've explained it clearly

**Comment by MartinFulgueiras** [comment]
Thanks for clarifying. Indeed my Nos. had the dot. Maybe it was a typo in a version or some other reason.
