### ISSUE TITLE
[BUG] Synced Woocommercer item title of variant item not contains template name 

### ISSUE THREAD

**Issue by bastelfeak** [dvdl16/woocommerce_fusion#110]
### Current Behavior

The plug in syncing the names of the variants but not add the template/head item name. So only the variant options are in the item title.

### Steps To Reproduce

Push sync from Woocommerce to ERPNext

### Expected Behavior

Either not overwrite the item title (check box for item sync is removed?) or add them together with the template name as prefix.

### Environment and Versions

```markdown
- Frappe Version: v15.35.0
- ERPNext Version: v15.30.0
- Custom App Version: v1.7.1
```

### Operating System

MacOS

### What browsers are you seeing the problem on?

Chrome

**Comment by dvdl16** [comment]
Thanks @bastelfeak. Can you give me an example/screenshot of your WooCommerce Product, and the corresponding ERPNext items?

**Comment by bastelfeak** [comment]
Example:

Template name: T-Shirt
Variants: 
Size: S, M, L
Color: black, white

The synced name for the single items is then
S, black
M, black
L, black
S, white
...

My expectation:
"T-Shirt, S, black"
...
