### ISSUE TITLE
Open up the license?

### ISSUE THREAD

**Issue by mepoland** [dvdl16/woocommerce_fusion#123]
### Is your feature request related to a problem? Please describe.

I'd like to use this code in my erpnext instance, but under "license" there is just a single person's name. My understanding is that means all rights reserved by that person. Can this be opened up to a collaborative project? What's the long term plan?
Apologies if I misunderstand the license or how this is supposed to work. I thought this looked more promising than libracore/WooCommerce due to its recent activity and focus on erpnext v15. But it appears the license would restrict me from using it.

### Describe the solution you'd like

See above

### Describe alternatives you've considered

See above

**Comment by dvdl16** [comment]
Thanks @mepoland 

The license will change to MIT in the near future.

I've submitted the app for review on Frappe Marketplace. As soon as it's approved I can update the license

**Comment by mepoland** [comment]
Fantastic! Looking forward to trying this out.
