### ISSUE TITLE
does it support v 15

### ISSUE THREAD

**Issue by Mar87iam** [dvdl16/woocommerce_fusion#23]
kindly woocomerce integratios was deprecated in erpnext 15

does woocommerce_fusion works well with erpnext 15

**Comment by dvdl16** [comment]
Hi, this has not been tested with v15, and it probably won't work with v15 if the erpnext woocommerce integration  has been deprecated, as it builds on top of that functionality. This will be compatible with v15 at some point in 2024.

**Comment by MauriceGrowteq** [comment]
Hi any update on when this would be available? Is there any way we can help?

**Comment by Maurice-Bijl** [comment]
Hi, What needs te be done to get this to work again? and how can I help?

**Comment by dvdl16** [comment]
> Hi, What needs te be done to get this to work again? and how can I help?

You can help with testing 👍

**Comment by alphaomegaphi** [comment]
Hi, 

I'm also interested in your integration. I have a clothing Woocommerce store to process customer orders, mainly guest customers, but also serve registered customers. Recently installed ERPNext and I'm in the process of setting up all master data. To me, the first objective I want to achieve is the ability to streamline the production and procurement planning processes.

I'm a bit new to ERPNext but experienced in Wordpress/Woocommerce. Happy to help progress this projec.t

**Comment by peterschingsbusgroup** [comment]
Hello, is there any chance to get this plugin back to work for v15? I would love to use my WP / Woocommerce with ERPNext. Happy to pay for the time spent on this, please contact me.

**Comment by dvdl16** [comment]
Intended for v15 since https://github.com/dvdl16/woocommerce_fusion/releases/tag/v1.0.0
