### ISSUE TITLE
Does it support Variants?

### ISSUE THREAD

**Issue by alphaomegaphi** [dvdl16/woocommerce_fusion#51]
Hi @dvdl16 I have been testing your repo, it does work very well syncing Orders and WC products into ERPNext, thank you.

Now, I noticed that when Sales Orders are created in ERPNext, the items populated in the items child table are the "parent" products from WC, not the variants, and those items are new Items created in ERPNext as "templates", even if assign the Woocommerce ID to existing item variants (in the Woocommerce ID/Woocommerce server child table).

So, couple of questions:

1. Are WC/ERPNext variations supported? if so, what's the correct configuration to sync items between both systems?
2. Why are items created as "template' items? I would expect that if no item found, then create a new variation under the respective Template (or a new template + variation if template does not exist).

On another topic. Thanks you for documenting your code, really makes a difference when implementing these apps.

**Comment by dvdl16** [comment]
Thanks for trying it out.

Unfortunately I haven't done _any_ testing with item variants. I can look into this when I have time next month

**Comment by alphaomegaphi** [comment]
Looking forward to that functionality, your repo looks promising.

**Comment by thomasoceguera** [comment]
Hi There, I'm curious to explore your app.  I have been using the old woocommerceconnector app created years ago and while it works fairly well, it does have some limitations.  But the reason I'm chiming in here is to offer some insight to how they do what the guy above is asking for.  There is a custom field added to all ERPN items via customize form.  This field is manually managed and the data that is added is the Product Post ID.  For the items with variants, simply create a template in ERPN, where you use the Parent Woo Product ID, then on the variants use the child Product ID in same slot.    I'm not a programmer so I'm not sure of the method that is used to manage this but  you can always check out the code here https://github.com/libracore/WooCommerceConnector
