### ISSUE TITLE
Ability to use existing products in erpnext

### ISSUE THREAD

**Issue by OwenHook** [dvdl16/woocommerce_fusion#52]
Hi,

I was wondering how to deal with existing products already in erpnext?  Is there a way to setup the connection using the product ID in woocommerce? I don't want to deal with auto creation of products into erpnext especially when there are hundreds already setup.

Thanks,
Owen

**Comment by dvdl16** [comment]
@OwenHook, yes you can link by Product ID on the Item page

![image](https://github.com/dvdl16/woocommerce_fusion/assets/4974009/c8c26acf-cfc4-4def-b86a-32b237f68611)

I'd suggest using Data Import to bulk update your items in ERPNext

**Comment by dvdl16** [comment]
See the new docs for more information:

https://woocommerce-fusion-docs.finfoot.tech/
