### ISSUE TITLE
Shipping Rule Fetching

### ISSUE THREAD

**Issue by bastelfeak** [dvdl16/woocommerce_fusion#81]
### Is your feature request related to a problem? Please describe.

If orders sync from Woocommerce it would be good to also sync the way of shipping / shipping rule.

### Describe the solution you'd like

With the sync of orders also fetch the shipping to with a connected shipping rule. 
Options:
1. Create a further DocType where Woocommerce shippings are saved and later the user can add fitting shipping rule
2. Create a new Shipping rule if it is not existing (problem, shipping rule can't be renamed), less flexible if you have more then one shop.

### Describe alternatives you've considered

Chosing the shipping rule on every single order is time consuming and a stupid task.

**Comment by dvdl16** [comment]
Thanks @bastelfeak.
Are you referring to "Shipping Zones" in WooCommerce?

![image](https://github.com/dvdl16/woocommerce_fusion/assets/4974009/c892bc08-9cce-4dc4-977d-d86ca7e1174c)

So the goal would be to link an ERPNext [Shipping Rules](https://docs.erpnext.com/docs/user/manual/en/shipping-rule) to such a WooCommerce Shipping Zone?
